name: Zip Skill

on:
  push:
    branches:
      - main
    paths:
      - "skills/charm-hyper/**"
  workflow_dispatch:

jobs:
  zip:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Zip Release
        uses: TheDoctor0/zip-release@0.7.6
        with:
          type: zip
          filename: hyper-charm-skill.zip
          directory: skills/charm-hyper
          exclusions: README.md

      - name: Upload zip artifact
        uses: actions/upload-artifact@v4
        with:
          name: hyper-charm-skill
          path: skills/charm-hyper/hyper-charm-skill.zip
